# Generated by Django 4.2.9 on 2026-02-12 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='heatmap_image',
            field=models.ImageField(blank=True, null=True, upload_to='heatmaps/%Y/%m/%d/'),
        ),
    ]
